### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by chenshen03** [fcakir/deep-mihash#1]
I run with following comman:
```matlab
demo_AP('cifar',32,'alexnet_ft','split',1,'nbins',32,'sigmf', [1 0],'lr', 1e-3,'lrstep',50,'epoch',100,'obj','mi','testInterval',10, 'batchSize', 256, 'metrics', 'AP')
```
However, the final mAP is very low (about 0.55).

Can you share the results on AlexNet and cifar-s1?

**Comment by fcakir** [comment]
Hi @chenshen03, we hadn't tested AlextNet on CIFAR. If you're willing to try AlexNet on CIFAR I suggest trying with different learning rates (`lr`), and/or increasing the sigmoid parameter (e.g. `sigmf = [30 0]`).
