### ISSUE TITLE
binary codes are not distinct

### ISSUE THREAD

**Issue by sobhanhemati** [fcakir/deep-mihash#2]
This method produces very limited distinct binary codes!- What is the difference between this method and simple one hot encoding?

**Comment by fcakir** [comment]
Hi @sobhanhemati , can you detail your results? One primary limitation of one-hot encodings are that they can be used only for "multi-class" datasets, in which images are associated with a single class only. The formulation in mihash, and in many other hashing techniques don't have this limitation. Also mihash results shown in the paper outperforms the (then) state-of-the-art. These results are reproducible with the code in this repo. So please try it out.  Closing for now, but we can re-open.
